name: Build, Push and Deploy Docker Image to Azure Web App
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Adjust if you're using a different version
 
      - name: Install dependencies
        run: npm install
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHB_PASSWORD }}
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME  }}/myapp:${{ github.sha }}
 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: solar-system1
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ vars.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}