name: Unit testing workflow

on:
  push:

jobs:
  Unit-testing:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
      MONGO_USERNAME: 'your-username-here'
      MONGO_PASSWORD: 'your-password-here'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js with version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Archive/store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./artifact

  upload:
    needs: Unit-testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload to Azure Blob Storage
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}
          name: test-results
          path: ./artifact/test-results.xml
